# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/mz_petalinux/mz_petalinux.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mz_petalinux || ORIG_REF_NAME==mz_petalinux} -quiet] -quiet

# IP: bd/mz_petalinux/ip/mz_petalinux_processing_system7_0_0/mz_petalinux_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mz_petalinux_processing_system7_0_0 || ORIG_REF_NAME==mz_petalinux_processing_system7_0_0} -quiet] -quiet

# XDC: bd/mz_petalinux/mz_petalinux_ooc.xdc
